# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment_accessor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .grpc.status import status_pb2 as grpc_dot_status_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='environment_accessor.proto',
  package='abc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x65nvironment_accessor.proto\x12\x03\x61\x62\x63\x1a\x18grpc/status/status.proto\"q\n\x16ObjectRetrievalRequest\x12\x18\n\x10logical_location\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\t\x12\x16\n\x0eobject_version\x18\x03 \x01(\x05\x12\x11\n\tpart_size\x18\x04 \x01(\x03\"X\n\x17ObjectRetrievalResponse\x12$\n\x06status\x18\x01 \x01(\x0b\x32\x12.google.rpc.StatusH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\tH\x00\x42\x07\n\x05value2a\n\x13\x45nvironmentAccessor\x12J\n\tgetObject\x12\x1b.abc.ObjectRetrievalRequest\x1a\x1c.abc.ObjectRetrievalResponse\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[grpc_dot_status_dot_status__pb2.DESCRIPTOR,])




_OBJECTRETRIEVALREQUEST = _descriptor.Descriptor(
  name='ObjectRetrievalRequest',
  full_name='abc.ObjectRetrievalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logical_location', full_name='abc.ObjectRetrievalRequest.logical_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_key', full_name='abc.ObjectRetrievalRequest.object_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_version', full_name='abc.ObjectRetrievalRequest.object_version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='part_size', full_name='abc.ObjectRetrievalRequest.part_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=174,
)


_OBJECTRETRIEVALRESPONSE = _descriptor.Descriptor(
  name='ObjectRetrievalResponse',
  full_name='abc.ObjectRetrievalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='abc.ObjectRetrievalResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='abc.ObjectRetrievalResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='abc.ObjectRetrievalResponse.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=176,
  serialized_end=264,
)

_OBJECTRETRIEVALRESPONSE.fields_by_name['status'].message_type = grpc_dot_status_dot_status__pb2._STATUS
_OBJECTRETRIEVALRESPONSE.oneofs_by_name['value'].fields.append(
  _OBJECTRETRIEVALRESPONSE.fields_by_name['status'])
_OBJECTRETRIEVALRESPONSE.fields_by_name['status'].containing_oneof = _OBJECTRETRIEVALRESPONSE.oneofs_by_name['value']
_OBJECTRETRIEVALRESPONSE.oneofs_by_name['value'].fields.append(
  _OBJECTRETRIEVALRESPONSE.fields_by_name['data'])
_OBJECTRETRIEVALRESPONSE.fields_by_name['data'].containing_oneof = _OBJECTRETRIEVALRESPONSE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['ObjectRetrievalRequest'] = _OBJECTRETRIEVALREQUEST
DESCRIPTOR.message_types_by_name['ObjectRetrievalResponse'] = _OBJECTRETRIEVALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectRetrievalRequest = _reflection.GeneratedProtocolMessageType('ObjectRetrievalRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTRETRIEVALREQUEST,
  '__module__' : 'environment_accessor_pb2'
  # @@protoc_insertion_point(class_scope:abc.ObjectRetrievalRequest)
  })
_sym_db.RegisterMessage(ObjectRetrievalRequest)

ObjectRetrievalResponse = _reflection.GeneratedProtocolMessageType('ObjectRetrievalResponse', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTRETRIEVALRESPONSE,
  '__module__' : 'environment_accessor_pb2'
  # @@protoc_insertion_point(class_scope:abc.ObjectRetrievalResponse)
  })
_sym_db.RegisterMessage(ObjectRetrievalResponse)



_ENVIRONMENTACCESSOR = _descriptor.ServiceDescriptor(
  name='EnvironmentAccessor',
  full_name='abc.EnvironmentAccessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=266,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='getObject',
    full_name='abc.EnvironmentAccessor.getObject',
    index=0,
    containing_service=None,
    input_type=_OBJECTRETRIEVALREQUEST,
    output_type=_OBJECTRETRIEVALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENVIRONMENTACCESSOR)

DESCRIPTOR.services_by_name['EnvironmentAccessor'] = _ENVIRONMENTACCESSOR

# @@protoc_insertion_point(module_scope)
